import { Hono } from "hono";
import { zValidator } from "@hono/zod-validator";
import { z } from "zod";
import { eq, and, sql, desc, gte, inArray } from "drizzle-orm";
import { createClient } from "@supabase/supabase-js";
import { db } from "../db/client.js";
import {
  students,
  studentInvites,
  profiles,
  studentAiProfiles,
  studentReports,
  lessonSessions,
  homeworkItems,
  todoItems,
  difficultyReports,
  studentInsights,
  studentCourseExamDates,
  studentCourses,
  courses,
  lessonBookings,
} from "../db/schema.js";
import { getIsraelToday } from "../lib/time.js";
import { authMiddleware, requireRole } from "../middleware/auth.js";
import { uuidParamSchema } from "../lib/validators.js";

const inviteSchema = z.object({
  full_name: z.string().min(1),
  grade_level: z.string().optional(),
  notes: z.string().optional(),
});

export const studentRoutes = new Hono()
  .use(authMiddleware)
  .use(requireRole("teacher"))

  // GET /students — teacher's roster
  // Includes unreviewed_difficulties count per student so the dashboard
  // can surface "needs attention" right on each student card without
  // needing a separate global difficulties feed.
  .get("/", async (c) => {
    const teacherId = c.get("userId");

    const roster = await db
      .select({
        id: students.id,
        teacher_id: students.teacher_id,
        onboarded_at: students.onboarded_at,
        grade_level: students.grade_level,
        notes: students.notes,
        full_name: profiles.full_name,
        email: profiles.email,
        avatar_url: profiles.avatar_url,
        ai_summary: studentAiProfiles.ai_summary,
        avg_completion_rate: studentAiProfiles.avg_completion_rate,
        weak_topics: studentAiProfiles.weak_topics,
        // Correlated subquery: cheap because difficulty_reports has an
        // index on (reviewed) and joining student_id is keyed.
        unreviewed_difficulties: sql<number>`(
          SELECT COUNT(*)::int FROM ${difficultyReports}
          WHERE ${difficultyReports.student_id} = ${students.id}
            AND ${difficultyReports.reviewed} = false
        )`,
      })
      .from(students)
      .innerJoin(profiles, eq(profiles.id, students.id))
      .leftJoin(
        studentAiProfiles,
        eq(studentAiProfiles.student_id, students.id)
      )
      .where(eq(students.teacher_id, teacherId));

    return c.json(roster);
  })

  // GET /students/:id — student detail
  .get("/:id", zValidator("param", uuidParamSchema), async (c) => {
    const teacherId = c.get("userId");
    const studentId = c.req.valid("param").id;

    const [student] = await db
      .select({
        id: students.id,
        teacher_id: students.teacher_id,
        onboarded_at: students.onboarded_at,
        grade_level: students.grade_level,
        notes: students.notes,
        background_note: students.background_note,
        primary_course_id: students.primary_course_id,
        full_name: profiles.full_name,
        email: profiles.email,
        // Pre-session briefing — generated by Claude after each lesson review.
        // Surfaced at the top of the student page so the teacher knows where
        // to pick up without scrolling history.
        next_session_briefing: studentAiProfiles.next_session_briefing,
      })
      .from(students)
      .innerJoin(profiles, eq(profiles.id, students.id))
      .leftJoin(
        studentAiProfiles,
        eq(studentAiProfiles.student_id, students.id)
      )
      .where(
        and(eq(students.id, studentId), eq(students.teacher_id, teacherId))
      )
      .limit(1);

    if (!student) return c.json({ error: "Student not found" }, 404);

    const studentCoursesList = await db
      .select({ id: courses.id, name: courses.name })
      .from(studentCourses)
      .innerJoin(courses, eq(courses.id, studentCourses.course_id))
      .where(and(eq(studentCourses.student_id, studentId), eq(studentCourses.is_active, true)))
      .orderBy(studentCourses.added_at);

    // Ensure primary_course_id is included even when it has no corresponding
    // student_courses row (legacy students whose course was set directly on the
    // student record before the student_courses join table existed).
    // Prepend so it appears first; skip if already present to avoid duplicates.
    //
    // IMPORTANT: only apply the fallback when there is NO student_courses row
    // at all (not even an archived one). If a row exists with is_active=false,
    // the course was archived by the teacher — respect that and do not re-surface
    // it here. The original check (course not in active list) is necessary but
    // not sufficient: after archive, the row exists but is filtered out above,
    // which is exactly the case we must NOT fall through to.
    if (
      student.primary_course_id &&
      !studentCoursesList.some((c) => c.id === student.primary_course_id)
    ) {
      // Check for any student_courses row (active OR archived).
      // • No row found → true legacy; add the fallback course.
      // • Row found (is_active=false) → archived; respect the archive, skip.
      const [anyRow] = await db
        .select({ course_id: studentCourses.course_id })
        .from(studentCourses)
        .where(
          and(
            eq(studentCourses.student_id, studentId),
            eq(studentCourses.course_id, student.primary_course_id)
          )
        )
        .limit(1);

      if (!anyRow) {
        const [primaryCourse] = await db
          .select({ id: courses.id, name: courses.name })
          .from(courses)
          .where(
            and(
              eq(courses.id, student.primary_course_id),
              eq(courses.teacher_id, teacherId)
            )
          )
          .limit(1);
        if (primaryCourse) {
          studentCoursesList.unshift(primaryCourse);
        }
      }
    }

    return c.json({ ...student, courses: studentCoursesList });
  })

  // ── Background note (long-form static context, rarely changes) ────────────
  .patch(
    "/:id/background",
    zValidator("param", uuidParamSchema),
    zValidator("json", z.object({ background_note: z.string().max(4000) })),
    async (c) => {
      const teacherId = c.get("userId");
      const studentId = c.req.valid("param").id;
      const { background_note } = c.req.valid("json");

      const trimmed = background_note.trim();

      const [updated] = await db
        .update(students)
        .set({ background_note: trimmed === "" ? null : trimmed })
        .where(
          and(eq(students.id, studentId), eq(students.teacher_id, teacherId))
        )
        .returning({ id: students.id, background_note: students.background_note });

      if (!updated) return c.json({ error: "Student not found" }, 404);
      return c.json(updated);
    }
  )

  // ── Insights (append-only log of "what helps this student") ───────────────
  // GET — newest first; the UI shows them in reverse chronological order
  .get("/:id/insights", zValidator("param", uuidParamSchema), async (c) => {
    const teacherId = c.get("userId");
    const studentId = c.req.valid("param").id;

    // Verify ownership
    const [owner] = await db
      .select({ id: students.id })
      .from(students)
      .where(
        and(eq(students.id, studentId), eq(students.teacher_id, teacherId))
      )
      .limit(1);
    if (!owner) return c.json({ error: "Student not found" }, 404);

    const rows = await db
      .select()
      .from(studentInsights)
      .where(eq(studentInsights.student_id, studentId))
      .orderBy(desc(studentInsights.created_at));

    return c.json(rows);
  })

  // POST — add a new insight (append-only; old ones never edited)
  .post(
    "/:id/insights",
    zValidator("param", uuidParamSchema),
    zValidator("json", z.object({ content: z.string().min(1).max(500) })),
    async (c) => {
      const teacherId = c.get("userId");
      const studentId = c.req.valid("param").id;
      const { content } = c.req.valid("json");

      // Verify ownership
      const [owner] = await db
        .select({ id: students.id })
        .from(students)
        .where(
          and(eq(students.id, studentId), eq(students.teacher_id, teacherId))
        )
        .limit(1);
      if (!owner) return c.json({ error: "Student not found" }, 404);

      const [inserted] = await db
        .insert(studentInsights)
        .values({
          student_id: studentId,
          teacher_id: teacherId,
          content: content.trim(),
        })
        .returning();

      return c.json(inserted, 201);
    }
  )

  // DELETE — remove an outdated insight (e.g. you got it wrong, or it's no
  // longer true). Path includes student_id so we can verify ownership cheaply.
  .delete(
    "/:id/insights/:insightId",
    zValidator(
      "param",
      z.object({
        id: z.string().uuid(),
        insightId: z.string().uuid(),
      })
    ),
    async (c) => {
      const teacherId = c.get("userId");
      const { id: studentId, insightId } = c.req.valid("param");

      const [deleted] = await db
        .delete(studentInsights)
        .where(
          and(
            eq(studentInsights.id, insightId),
            eq(studentInsights.student_id, studentId),
            eq(studentInsights.teacher_id, teacherId)
          )
        )
        .returning({ id: studentInsights.id });

      if (!deleted) return c.json({ error: "Insight not found" }, 404);
      return c.json({ message: "Insight removed" });
    }
  )

  // GET /students/:id/profile — AI profile + stats
  .get("/:id/profile", zValidator("param", uuidParamSchema), async (c) => {
    const teacherId = c.get("userId");
    const studentId = c.req.valid("param").id;

    // Verify ownership
    const [owner] = await db
      .select({ id: students.id })
      .from(students)
      .where(
        and(eq(students.id, studentId), eq(students.teacher_id, teacherId))
      )
      .limit(1);

    if (!owner) return c.json({ error: "Student not found" }, 404);

    const [aiProfile] = await db
      .select()
      .from(studentAiProfiles)
      .where(eq(studentAiProfiles.student_id, studentId))
      .limit(1);

    return c.json(aiProfile ?? null);
  })

  // GET /students/:id/report — latest report
  .get("/:id/report", zValidator("param", uuidParamSchema), async (c) => {
    const teacherId = c.get("userId");
    const studentId = c.req.valid("param").id;

    const [owner] = await db
      .select({ id: students.id })
      .from(students)
      .where(
        and(eq(students.id, studentId), eq(students.teacher_id, teacherId))
      )
      .limit(1);

    if (!owner) return c.json({ error: "Student not found" }, 404);

    const [report] = await db
      .select()
      .from(studentReports)
      .where(eq(studentReports.student_id, studentId))
      .orderBy(studentReports.generated_at)
      .limit(1);

    return c.json(report ?? null);
  })

  // PATCH /students/:id/notes
  .patch(
    "/:id/notes",
    zValidator("param", uuidParamSchema),
    zValidator("json", z.object({ notes: z.string() })),
    async (c) => {
      const teacherId = c.get("userId");
      const studentId = c.req.valid("param").id;
      const { notes } = c.req.valid("json");

      const [updated] = await db
        .update(students)
        .set({ notes })
        .where(
          and(eq(students.id, studentId), eq(students.teacher_id, teacherId))
        )
        .returning();

      if (!updated) return c.json({ error: "Student not found" }, 404);
      return c.json(updated);
    }
  )

  // DELETE /students/:id — remove a student entirely
  .delete("/:id", zValidator("param", uuidParamSchema), async (c) => {
    const teacherId = c.get("userId");
    const studentId = c.req.valid("param").id;

    // Verify ownership
    const [student] = await db
      .select({ id: students.id })
      .from(students)
      .where(
        and(eq(students.id, studentId), eq(students.teacher_id, teacherId))
      )
      .limit(1);

    if (!student) return c.json({ error: "Student not found" }, 404);

    // Delete student row (cascades to profile via FK, which cascades lessons, homework, etc.)
    await db.delete(students).where(eq(students.id, studentId));
    await db.delete(profiles).where(eq(profiles.id, studentId));

    // Delete the Supabase auth user too
    try {
      const supabase = createClient(
        process.env["SUPABASE_URL"]!,
        process.env["SUPABASE_SERVICE_ROLE_KEY"]!
      );
      await supabase.auth.admin.deleteUser(studentId);
    } catch {
      // Auth user may already be gone — that's fine
    }

    return c.json({ message: "Student deleted" });
  })

  // PUT /students/:id/exam-date — set or clear the per-(student, course) exam
  // date override. The learning-map endpoint reads this with priority over
  // courses.exam_date, so each student can have their own deadline even when
  // they're working through the same course as another student.
  //
  // Body: { course_id, exam_date }  — exam_date null/undefined clears the row.
  .put(
    "/:id/exam-date",
    zValidator("param", uuidParamSchema),
    zValidator(
      "json",
      z.object({
        course_id: z.string().uuid(),
        exam_date: z.string().nullable().optional(),
      })
    ),
    async (c) => {
      const teacherId = c.get("userId");
      const studentId = c.req.valid("param").id;
      const { course_id, exam_date } = c.req.valid("json");

      // Ownership: verify the teacher owns both the student and the course.
      // Without this either side could leak data via crafted IDs.
      const [owner] = await db
        .select({ id: students.id })
        .from(students)
        .where(
          and(
            eq(students.id, studentId),
            eq(students.teacher_id, teacherId)
          )
        )
        .limit(1);
      if (!owner) return c.json({ error: "Student not found" }, 404);

      const [courseOwner] = await db
        .select({ id: courses.id })
        .from(courses)
        .where(
          and(eq(courses.id, course_id), eq(courses.teacher_id, teacherId))
        )
        .limit(1);
      if (!courseOwner) return c.json({ error: "Course not found" }, 404);

      // null/empty clears the override. Any value sets/replaces it.
      if (!exam_date) {
        await db
          .delete(studentCourseExamDates)
          .where(
            and(
              eq(studentCourseExamDates.student_id, studentId),
              eq(studentCourseExamDates.course_id, course_id)
            )
          );
        return c.json({ exam_date: null });
      }

      const dt = new Date(exam_date);
      if (isNaN(dt.getTime())) {
        return c.json({ error: "Invalid exam_date" }, 400);
      }

      // Upsert. The (student_id, course_id) tuple is unique by index.
      await db
        .insert(studentCourseExamDates)
        .values({
          student_id: studentId,
          course_id,
          exam_date: dt,
        })
        .onConflictDoUpdate({
          target: [
            studentCourseExamDates.student_id,
            studentCourseExamDates.course_id,
          ],
          set: { exam_date: dt, updated_at: new Date() },
        });

      return c.json({ exam_date: dt.toISOString() });
    }
  )

  // GET /students/:id/exam-date?course_id=X — read the current effective exam
  // date for this student in this course. Returns the override if set,
  // otherwise the course default. Used by the teacher's student-map UI to
  // pre-fill the date picker.
  .get(
    "/:id/exam-date",
    zValidator("param", uuidParamSchema),
    zValidator(
      "query",
      z.object({ course_id: z.string().uuid() })
    ),
    async (c) => {
      const teacherId = c.get("userId");
      const studentId = c.req.valid("param").id;
      const { course_id } = c.req.valid("query");

      const [owner] = await db
        .select({ id: students.id })
        .from(students)
        .where(
          and(
            eq(students.id, studentId),
            eq(students.teacher_id, teacherId)
          )
        )
        .limit(1);
      if (!owner) return c.json({ error: "Student not found" }, 404);

      const [override] = await db
        .select({ exam_date: studentCourseExamDates.exam_date })
        .from(studentCourseExamDates)
        .where(
          and(
            eq(studentCourseExamDates.student_id, studentId),
            eq(studentCourseExamDates.course_id, course_id)
          )
        )
        .limit(1);

      const [course] = await db
        .select({ exam_date: courses.exam_date })
        .from(courses)
        .where(eq(courses.id, course_id))
        .limit(1);

      return c.json({
        override_exam_date: override?.exam_date?.toISOString() ?? null,
        course_exam_date: course?.exam_date?.toISOString() ?? null,
        effective_exam_date:
          override?.exam_date?.toISOString() ??
          course?.exam_date?.toISOString() ??
          null,
      });
    }
  )

  // POST /students/:id/courses — assign a course to a student (or replace
  // the current primary course). The learning-map endpoint uses primary_course_id
  // as the fallback when the student has no lessons yet, so this is the
  // canonical way to prime the map for a freshly-onboarded student or to
  // switch their active course.
  //
  // Idempotent: calling with the same course_id twice is a no-op (returns 200).
  // Conflict: if the student already has this exact course set, returns 200.
  .post(
    "/:id/courses",
    zValidator("param", uuidParamSchema),
    zValidator("json", z.object({ course_id: z.string().uuid() })),
    async (c) => {
      const teacherId = c.get("userId");
      const studentId = c.req.valid("param").id;
      const { course_id } = c.req.valid("json");

      // Verify teacher owns the student
      const [student] = await db
        .select({ id: students.id, primary_course_id: students.primary_course_id })
        .from(students)
        .where(and(eq(students.id, studentId), eq(students.teacher_id, teacherId)))
        .limit(1);
      if (!student) return c.json({ error: "Student not found" }, 404);

      // Verify teacher owns the course
      const [course] = await db
        .select({ id: courses.id, name: courses.name })
        .from(courses)
        .where(and(eq(courses.id, course_id), eq(courses.teacher_id, teacherId)))
        .limit(1);
      if (!course) return c.json({ error: "Course not found" }, 404);

      // Check if a student_courses row already exists (active or archived).
      // • is_active = true  → already enrolled, nothing to do (409)
      // • is_active = false → previously archived; reactivate in-place
      const [existingAssignment] = await db
        .select({ is_active: studentCourses.is_active })
        .from(studentCourses)
        .where(and(eq(studentCourses.student_id, studentId), eq(studentCourses.course_id, course_id)))
        .limit(1);
      if (existingAssignment) {
        if (existingAssignment.is_active) {
          return c.json({ error: "Course already assigned to student" }, 409);
        }
        // Reactivate the archived row instead of inserting a duplicate.
        await db
          .update(studentCourses)
          .set({ is_active: true })
          .where(and(eq(studentCourses.student_id, studentId), eq(studentCourses.course_id, course_id)));
        return c.json({ student_id: studentId, course_id, course_name: course.name }, 200);
      }

      // Set primary_course_id only when the student has none yet.
      // Subsequent course additions must NOT overwrite the existing primary
      // course — otherwise the original course (e.g. "Algebra 1") would
      // disappear from the course picker once a second course is added.
      // The learning-map fallback path (primary_course_id → student_courses)
      // continues to work correctly because the first-assigned course remains
      // the primary.
      if (!student.primary_course_id) {
        await db
          .update(students)
          .set({ primary_course_id: course_id })
          .where(eq(students.id, studentId));
      }

      // Add to student_courses join table
      await db
        .insert(studentCourses)
        .values({ student_id: studentId, course_id })
        .onConflictDoNothing();

      return c.json({ student_id: studentId, course_id, course_name: course.name }, 201);
    }
  )

  // PATCH /students/:id/courses/:courseId/archive
  // Soft-disables a course for a student by setting is_active = false.
  // Does NOT delete any rows, lessons, or session history.
  //
  // 404 — student not found, or course not assigned to student.
  // 409 — course is already archived.
  // 409 — student has future active lessons for this course (unless ?force=true).
  //        Body: { error: string, futureCount: number }
  // 200 — success.
  //
  // Reactivation: POST /students/:id/courses with the same course_id will
  // set is_active = true again.
  .patch(
    "/:id/courses/:courseId/archive",
    zValidator(
      "param",
      z.object({ id: z.string().uuid(), courseId: z.string().uuid() })
    ),
    zValidator(
      "query",
      z.object({ force: z.enum(["true", "false"]).optional() })
    ),
    async (c) => {
      const teacherId = c.get("userId");
      const { id: studentId, courseId } = c.req.valid("param");
      const force = c.req.valid("query").force === "true";

      // Verify teacher owns the student
      const [student] = await db
        .select({ id: students.id, primary_course_id: students.primary_course_id })
        .from(students)
        .where(and(eq(students.id, studentId), eq(students.teacher_id, teacherId)))
        .limit(1);
      if (!student) return c.json({ error: "Student not found" }, 404);

      // Verify the student_courses row exists
      const [row] = await db
        .select({ is_active: studentCourses.is_active })
        .from(studentCourses)
        .where(
          and(
            eq(studentCourses.student_id, studentId),
            eq(studentCourses.course_id, courseId)
          )
        )
        .limit(1);

      if (!row) return c.json({ error: "Course not assigned to this student" }, 404);
      if (!row.is_active) return c.json({ error: "Course is already archived" }, 409);

      // Unless force=true, block if there are upcoming active lessons for this
      // student/course combination. "Future" = date >= Israel today; "active" =
      // status in approved / pending / cancel_requested.
      //
      // futureCount reports REAL LESSON GROUPS, not lesson_bookings rows.
      // A 1-hour lesson is stored as 2 consecutive 30-min slots; a 1.5-hour
      // lesson as 3; etc.
      //
      // Grouping rule (in priority order):
      //   1. gcal_event_id is the authoritative group key — slots created
      //      together always share one gcal_event_id (set atomically by
      //      bookings.ts after the GCal event is created). This means
      //      back-to-back lessons (e.g. 10:00-11:00 and 11:00-12:00) with
      //      DIFFERENT gcal_event_ids are correctly counted as TWO lessons
      //      even though their times are consecutive.
      //   2. NULL gcal_event_id (rare — gcal creation failed at the time, or
      //      a very old booking pre-dates that field) falls back to the
      //      consecutive-slot rule: same date + same status + previous
      //      end_time === current start_time → same lesson.
      //
      // A gcal-tagged slot ALWAYS breaks any synthetic (null-gcal) chain,
      // so a slot with gcal_event_id cannot be merged with a null-gcal
      // neighbour. This is the safe direction (over-warn, never under-warn).
      if (!force) {
        const today = getIsraelToday();
        const futureSlots = await db
          .select({
            date: lessonBookings.date,
            start_time: lessonBookings.start_time,
            end_time: lessonBookings.end_time,
            status: lessonBookings.status,
            gcal_event_id: lessonBookings.gcal_event_id,
          })
          .from(lessonBookings)
          .where(
            and(
              eq(lessonBookings.student_id, studentId),
              eq(lessonBookings.course_id, courseId),
              gte(lessonBookings.date, today),
              inArray(lessonBookings.status, ["approved", "pending", "cancel_requested"])
            )
          )
          .orderBy(lessonBookings.date, lessonBookings.start_time);

        const groupKeys = new Set<string>();
        let lastDate: string | null = null;
        let lastEnd: string | null = null;
        let lastStatus: string | null = null;
        let activeSyntheticKey: string | null = null;
        let syntheticIdx = 0;

        for (const s of futureSlots) {
          if (s.gcal_event_id) {
            // Real lesson group — every slot of the same lesson shares this id.
            groupKeys.add(`g:${s.gcal_event_id}`);
            // A gcal-tagged slot breaks any in-flight synthetic chain so a
            // null-gcal neighbour can never merge into it.
            activeSyntheticKey = null;
            lastDate = null;
            lastEnd = null;
            lastStatus = null;
          } else {
            const continuesChain =
              activeSyntheticKey !== null &&
              s.date === lastDate &&
              s.start_time === lastEnd &&
              s.status === lastStatus;
            if (!continuesChain) {
              activeSyntheticKey = `s:${syntheticIdx++}`;
            }
            groupKeys.add(activeSyntheticKey!);
            lastDate = s.date;
            lastEnd = s.end_time;
            lastStatus = s.status;
          }
        }

        if (groupKeys.size > 0) {
          return c.json(
            {
              error: "Student has future active lessons for this course",
              futureCount: groupKeys.size,
            },
            409
          );
        }
      }

      // Soft-archive: flip the flag. No rows are deleted.
      await db
        .update(studentCourses)
        .set({ is_active: false })
        .where(
          and(
            eq(studentCourses.student_id, studentId),
            eq(studentCourses.course_id, courseId)
          )
        );

      // Keep primary_course_id pointing at an active course only. If we just
      // archived the primary, move it to the oldest remaining active course,
      // or null when none remain. Other consumers (e.g. the learning-map
      // fallback) rely on primary never pointing at an archived course.
      if (student.primary_course_id === courseId) {
        const [nextActive] = await db
          .select({ course_id: studentCourses.course_id })
          .from(studentCourses)
          .where(
            and(
              eq(studentCourses.student_id, studentId),
              eq(studentCourses.is_active, true)
            )
          )
          .orderBy(studentCourses.added_at)
          .limit(1);
        await db
          .update(students)
          .set({ primary_course_id: nextActive?.course_id ?? null })
          .where(eq(students.id, studentId));
      }

      return c.json({ student_id: studentId, course_id: courseId, is_active: false });
    }
  )

  // POST /students/invite — create a pending invite token (no auth user yet)
  // The student will use the token to register with their own email+password.
  .post("/invite", zValidator("json", inviteSchema), async (c) => {
    const teacherId = c.get("userId");
    const body = c.req.valid("json");

    const token = crypto.randomUUID();

    const [invite] = await db
      .insert(studentInvites)
      .values({
        token,
        teacher_id: teacherId,
        full_name: body.full_name,
        grade_level: body.grade_level,
        notes: body.notes,
      })
      .returning();

    const inviteUrl = `${process.env["NEXT_PUBLIC_APP_URL"]}/register?token=${token}`;

    return c.json({
      invite_token: invite!.token,
      invite_url: inviteUrl,
      full_name: invite!.full_name,
    });
  });
