-- 015_next_session_briefing.sql
-- Adds a pre-session briefing field to student_ai_profiles.
-- Generated by Claude after each lesson review; displayed at the top of
-- the student page so the teacher knows where to pick up.

ALTER TABLE student_ai_profiles
  ADD COLUMN IF NOT EXISTS next_session_briefing TEXT;
